[package]
name = "erabi"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
dotenvy = "0.15.7"
secrecy = "0.10.3"
thiserror = "2.0.20"
tokio = { version = "1.53.1", features = ["time"] }
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt", "test-util", "time"] }
