[package]
name = "erabi-crawler"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
erabi-db = { version = "0.1.0", path = "../erabi-db" }
erabi-domain = { version = "0.1.0", path = "../erabi-domain" }
thiserror = "2.0.20"
url = "2.5.8"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread", "sync"] }
